### ISSUE TITLE
How do I prepare the OTB dataset?

### ISSUE THREAD

**Issue by PIN-FENG** [lizhou-cs/JointNLT#12]
Dear Zhou,

Thanks for your excellent work!

How do I prepare the OTB dataset?
How to download the OTB_query_test, OTB_query_train, and OTB_videos?
--OTB_sentences
         |-- OTB_query_test
         |-- OTB_query_train
         |-- OTB_videos

Thank you!

**Comment by mengmimi** [comment]
Hello, I have also encountered the same problem. How did you solve it? Looking forward to your answer very much

**Comment by xwhzz** [comment]
You can get help from #6.
