### ISSUE TITLE
Network is not of correct type

### ISSUE THREAD

**Issue by LanserSoda** [lizhou-cs/JointNLT#14]
尝试在训练时加载JointNLT_ep0300.pth.tar权重模型，因checkpoint_dict['net_type']为transnlt，与net类型jointnlt不一致，报错：Network is not of correct type. 代码中没有找到transnlt相关的yaml文件，请问该如何解决？

**Comment by lizhou-cs** [comment]
Hello,  I've just made a change to the network name, and it won't have any actual impact.
