### ISSUE TITLE
template is no used in training code?

### ISSUE THREAD

**Issue by laisimiao** [lizhou-cs/JointNLT#2]
I look through the training code, and want to confirm that whether settings about template variable are not used ?
and i am confused with this code paragraph:
https://github.com/lizhou-cs/JointNLT/blob/2ed17156ba362faabeeb03c5682c0155401beb88/lib/train/actors/jointnltActor.py#L98-L102
in try, there is no return, so what's the purpose of running codes within try context?

**Comment by lizhou-cs** [comment]
Thank you for your question.
To ensure consistency between training and inference, we conduct grounding to obtain a target box during training, and then crop the corresponding position on the grounding patch to obtain the template. Specific implementation details can be found in the ​[​``` __call__​``` ](https://github.com/lizhou-cs/JointNLT/blob/main/lib/train/data/processing.py#L611-L664)method of the ​[```TemplateProcessing```](https://github.com/lizhou-cs/JointNLT/blob/main/lib/train/data/processing.py#L536)​ class. The template variables are also used in the ​[```TemplateProcessing```](https://github.com/lizhou-cs/JointNLT/blob/main/lib/train/data/processing.py#L536)​ class. The reason for the absence of a return value is that we add the variables of the template into the dictionary of the data.
I apologize for not providing detailed comments in the TemplateProcessing class, but I have now updated them.

**Comment by laisimiao** [comment]
OK, I totally understand it. Thanks.
