### ISSUE TITLE
temporal and roi_queue no use in inference phase?

### ISSUE THREAD

**Issue by laisimiao** [lizhou-cs/JointNLT#5]

**Comment by lizhou-cs** [comment]
I'm sorry I made a mistake while organizing the code. I have updated the new code.
https://github.com/lizhou-cs/JointNLT/blob/bc8cc2fab9beec44e2f333ed4ed4611a73ca8ee2/lib/test/tracker/jointnlt.py#L123-L130

**Comment by laisimiao** [comment]
okay
