### ISSUE TITLE
About some training problems of grounding and tracking sub-task ?

### ISSUE THREAD

**Issue by Azong-HQU** [lizhou-cs/JointNLT#7]
作者您好，请问方便提供模型训练的log文件吗？或者麻烦告诉我一下：grounding需要训练到多少个epoch后才能稳定，即grounding预测框与GT的IoU>阈值(0.5)，另外地，tracking是在第几个epoch才能正常被训练，tracking loss不再需要被置为0 ？

麻烦作者能在有空时回复我一下，万分感谢！！！

**Comment by lizhou-cs** [comment]
你好，感谢你的关注。 grounding的训练和tracking的训练时均会稳定增长，我建议你先将 self.settings.num_search设为1正常训练50epoch后，随后将 self.settings.num_search设为2 按照视频序列的方法继续训练模型。

**Comment by Azong-HQU** [comment]
嗯嗯好的，我稍后重新试试，请问其他地方还需要注意什么吗？

**Comment by lizhou-cs** [comment]
没有其他需要特别注意的地方，后续如果有其他问题也欢迎你提出。
